/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCheckTodo {
        "done": boolean;
        "n": number;
        "text": string;
    }
    interface MyHello {
        "name": string;
    }
    interface MyLifecycle {
    }
    interface MyName {
        "first": string;
        "last": string;
    }
    interface MyStore {
    }
    interface MyTodo {
    }
}
export interface MyCheckTodoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyCheckTodoElement;
}
declare global {
    interface HTMLMyCheckTodoElement extends Components.MyCheckTodo, HTMLStencilElement {
    }
    var HTMLMyCheckTodoElement: {
        prototype: HTMLMyCheckTodoElement;
        new (): HTMLMyCheckTodoElement;
    };
    interface HTMLMyHelloElement extends Components.MyHello, HTMLStencilElement {
    }
    var HTMLMyHelloElement: {
        prototype: HTMLMyHelloElement;
        new (): HTMLMyHelloElement;
    };
    interface HTMLMyLifecycleElement extends Components.MyLifecycle, HTMLStencilElement {
    }
    var HTMLMyLifecycleElement: {
        prototype: HTMLMyLifecycleElement;
        new (): HTMLMyLifecycleElement;
    };
    interface HTMLMyNameElement extends Components.MyName, HTMLStencilElement {
    }
    var HTMLMyNameElement: {
        prototype: HTMLMyNameElement;
        new (): HTMLMyNameElement;
    };
    interface HTMLMyStoreElement extends Components.MyStore, HTMLStencilElement {
    }
    var HTMLMyStoreElement: {
        prototype: HTMLMyStoreElement;
        new (): HTMLMyStoreElement;
    };
    interface HTMLMyTodoElement extends Components.MyTodo, HTMLStencilElement {
    }
    var HTMLMyTodoElement: {
        prototype: HTMLMyTodoElement;
        new (): HTMLMyTodoElement;
    };
    interface HTMLElementTagNameMap {
        "my-check-todo": HTMLMyCheckTodoElement;
        "my-hello": HTMLMyHelloElement;
        "my-lifecycle": HTMLMyLifecycleElement;
        "my-name": HTMLMyNameElement;
        "my-store": HTMLMyStoreElement;
        "my-todo": HTMLMyTodoElement;
    }
}
declare namespace LocalJSX {
    interface MyCheckTodo {
        "done": boolean;
        "n": number;
        "onTodo"?: (event: MyCheckTodoCustomEvent<number>) => void;
        "text": string;
    }
    interface MyHello {
        "name"?: string;
    }
    interface MyLifecycle {
    }
    interface MyName {
        "first"?: string;
        "last"?: string;
    }
    interface MyStore {
    }
    interface MyTodo {
    }
    interface IntrinsicElements {
        "my-check-todo": MyCheckTodo;
        "my-hello": MyHello;
        "my-lifecycle": MyLifecycle;
        "my-name": MyName;
        "my-store": MyStore;
        "my-todo": MyTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-check-todo": LocalJSX.MyCheckTodo & JSXBase.HTMLAttributes<HTMLMyCheckTodoElement>;
            "my-hello": LocalJSX.MyHello & JSXBase.HTMLAttributes<HTMLMyHelloElement>;
            "my-lifecycle": LocalJSX.MyLifecycle & JSXBase.HTMLAttributes<HTMLMyLifecycleElement>;
            "my-name": LocalJSX.MyName & JSXBase.HTMLAttributes<HTMLMyNameElement>;
            "my-store": LocalJSX.MyStore & JSXBase.HTMLAttributes<HTMLMyStoreElement>;
            "my-todo": LocalJSX.MyTodo & JSXBase.HTMLAttributes<HTMLMyTodoElement>;
        }
    }
}
